### ISSUE TITLE
メディアクエリを共通で持ちたい

### ISSUE THREAD

**Issue by eatski** [mosa-architect-study/replace-kintai#111]
現状メディアクエリ（`max-width:480px`）を各所にベタ書きしてるのよくないのでthemeとかに逃がしたい

**Comment by eatski** [comment]
```css
@media (max-width: 480px) {
    width: 244px;
  }
```
